#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TeamEventApp.Droid.Resource", IsApplication=true)]

namespace TeamEventApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int com_facebook_foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_logout_text = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int com_facebook_object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int com_facebook_object_type = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_preset_size = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_tooltip_mode = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_button_background_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_button_background_color_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_button_background_color_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_button_like_background_color_selected = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_button_login_silver_background_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_button_send_background_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_button_send_background_color_pressed = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_likeboxcountview_border_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeboxcountview_text_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_text_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_share_button_text_color = 2131034124;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060013
			public const int activity_horizontal_margin = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int activity_vertical_margin = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_likeboxcountview_border_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_likeboxcountview_border_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_likeboxcountview_caret_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_likeboxcountview_caret_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_likeboxcountview_text_padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_likeboxcountview_text_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_likeview_edge_padding = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_likeview_internal_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_likeview_text_size = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_profilepictureview_preset_size_large = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_share_button_padding_bottom = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_share_button_padding_left = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_share_button_padding_right = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_share_button_padding_top = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_share_button_text_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_tooltip_horizontal_padding = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int fab_margin = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int login_top_margin = 2131099670;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_like_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_like_icon_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_login_silver_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_send_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_send_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_close = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_profile_picture_blank_portrait = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_profile_picture_blank_square = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_tooltip_black_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_tooltip_black_bottomnub = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_tooltip_black_topnub = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_tooltip_black_xout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_blue_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_blue_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_blue_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_blue_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int messenger_bubble_large_blue = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int messenger_bubble_large_white = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int messenger_bubble_small_blue = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int messenger_bubble_small_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int messenger_button_blue_bg_round = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int messenger_button_blue_bg_selector = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int messenger_button_send_round_shadow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int messenger_button_white_bg_round = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int messenger_button_white_bg_selector = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080026
			public const int List = 2131230758;
			
			// aapt resource value: 0x7f080040
			public const int about_item = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int action_settings = 2131230785;
			
			// aapt resource value: 0x7f080025
			public const int addGroupButton = 2131230757;
			
			// aapt resource value: 0x7f080020
			public const int adminTextView = 2131230752;
			
			// aapt resource value: 0x7f08000c
			public const int automatic = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int bottom = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int box_count = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int button = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int center = 2131230729;
			
			// aapt resource value: 0x7f08002c
			public const int champsEmail = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int champsMdp = 2131230767;
			
			// aapt resource value: 0x7f080029
			public const int champsNom = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int champsPrenom = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int champsPseudo = 2131230765;
			
			// aapt resource value: 0x7f080031
			public const int cnx_appName_text = 2131230769;
			
			// aapt resource value: 0x7f080034
			public const int cnx_connection_btn = 2131230772;
			
			// aapt resource value: 0x7f080032
			public const int cnx_email_text = 2131230770;
			
			// aapt resource value: 0x7f080036
			public const int cnx_fpwd_text = 2131230774;
			
			// aapt resource value: 0x7f080033
			public const int cnx_pwd_text = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int cnx_register_text = 2131230773;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_body_frame = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int com_facebook_button_xout = 2131230746;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_fragment_container = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_login_activity_progress_bar = 2131230743;
			
			// aapt resource value: 0x7f08001c
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int com_facebook_tooltip_bubble_view_text_body = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int display_always = 2131230733;
			
			// aapt resource value: 0x7f080030
			public const int enregistrerButton = 2131230768;
			
			// aapt resource value: 0x7f08003f
			public const int event_manager_item = 2131230783;
			
			// aapt resource value: 0x7f080024
			public const int eventsTextView = 2131230756;
			
			// aapt resource value: 0x7f080013
			public const int formTable = 2131230739;
			
			// aapt resource value: 0x7f08001d
			public const int groupNameTextView = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int groupTable = 2131230750;
			
			// aapt resource value: 0x7f08003e
			public const int group_manager_item = 2131230782;
			
			// aapt resource value: 0x7f080007
			public const int inline = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int large = 2131230735;
			
			// aapt resource value: 0x7f080038
			public const int launcher_appname_text = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int launcher_legend_text = 2131230777;
			
			// aapt resource value: 0x7f08000a
			public const int left = 2131230730;
			
			// aapt resource value: 0x7f080022
			public const int membersTextView = 2131230754;
			
			// aapt resource value: 0x7f080042
			public const int menu_add = 2131230786;
			
			// aapt resource value: 0x7f08003b
			public const int menu_search = 2131230779;
			
			// aapt resource value: 0x7f080043
			public const int messenger_send_button = 2131230787;
			
			// aapt resource value: 0x7f08000e
			public const int never_display = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int nomGrpEditText = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int normal = 2131230736;
			
			// aapt resource value: 0x7f08003c
			public const int notifications_item = 2131230780;
			
			// aapt resource value: 0x7f080000
			public const int open_graph = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int page = 2131230721;
			
			// aapt resource value: 0x7f08003d
			public const int profile_item = 2131230781;
			
			// aapt resource value: 0x7f08004c
			public const int reg_cnxFacebook_btn = 2131230796;
			
			// aapt resource value: 0x7f080049
			public const int reg_confPwd_text = 2131230793;
			
			// aapt resource value: 0x7f080047
			public const int reg_email_text = 2131230791;
			
			// aapt resource value: 0x7f080045
			public const int reg_fname_text = 2131230789;
			
			// aapt resource value: 0x7f080044
			public const int reg_legend_text = 2131230788;
			
			// aapt resource value: 0x7f080046
			public const int reg_lname_text = 2131230790;
			
			// aapt resource value: 0x7f08004b
			public const int reg_or_text = 2131230795;
			
			// aapt resource value: 0x7f080048
			public const int reg_pwd_text = 2131230792;
			
			// aapt resource value: 0x7f08004d
			public const int reg_signin_text = 2131230797;
			
			// aapt resource value: 0x7f08004a
			public const int register_btn = 2131230794;
			
			// aapt resource value: 0x7f08004f
			public const int resetpass_email_text = 2131230799;
			
			// aapt resource value: 0x7f08004e
			public const int resetpass_legend_text = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int resetpass_send_btn = 2131230800;
			
			// aapt resource value: 0x7f08000b
			public const int right = 2131230731;
			
			// aapt resource value: 0x7f080027
			public const int scrollView1 = 2131230759;
			
			// aapt resource value: 0x7f080011
			public const int small = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int standard = 2131230725;
			
			// aapt resource value: 0x7f080012
			public const int textView = 2131230738;
			
			// aapt resource value: 0x7f08001f
			public const int textView1 = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int textView2 = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int textView3 = 2131230755;
			
			// aapt resource value: 0x7f08002b
			public const int textView4 = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int textView5 = 2131230766;
			
			// aapt resource value: 0x7f080028
			public const int textView6 = 2131230760;
			
			// aapt resource value: 0x7f080008
			public const int top = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int unknown = 2131230722;
			
			// aapt resource value: 0x7f080015
			public const int validGroup = 2131230741;
			
			// aapt resource value: 0x7f080037
			public const int versAccueilButton = 2131230775;
			
			// aapt resource value: 0x7f08003a
			public const int versConnexionButton = 2131230778;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddGroup = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_activity_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_login_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_tooltip_bubble = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EventManager = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Group = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GroupManager = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Inscription = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Menu = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Menu_add_option = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int messenger_button_send_blue_large = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int messenger_button_send_blue_round = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int messenger_button_send_blue_small = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int messenger_button_send_white_large = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int messenger_button_send_white_round = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int messenger_button_send_white_small = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Notifications = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int RegisterAccount = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ResetPassword = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040030
			public const int action_about = 2130968624;
			
			// aapt resource value: 0x7f04002d
			public const int action_event = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int action_group = 2130968622;
			
			// aapt resource value: 0x7f04002b
			public const int action_notifications = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int action_profile = 2130968620;
			
			// aapt resource value: 0x7f04002f
			public const int action_settings = 2130968623;
			
			// aapt resource value: 0x7f040028
			public const int already_member = 2130968616;
			
			// aapt resource value: 0x7f040011
			public const int app_name = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_image_download_unknown_error = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_internet_permission_error_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_internet_permission_error_title = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_like_button_liked = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_like_button_not_liked = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_loading = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_loginview_cancel_action = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_loginview_log_in_button = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loginview_log_in_button_long = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_log_out_action = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_loginview_log_out_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_loginview_logged_in_as = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_send_button_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_share_button_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_tooltip_default = 2130968591;
			
			// aapt resource value: 0x7f040025
			public const int confirm_password = 2130968613;
			
			// aapt resource value: 0x7f04001e
			public const int email = 2130968606;
			
			// aapt resource value: 0x7f040014
			public const int facebook_app_id = 2130968596;
			
			// aapt resource value: 0x7f040023
			public const int first_name = 2130968611;
			
			// aapt resource value: 0x7f040021
			public const int forgot_mdp = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int label_about = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int label_add_group = 2130968605;
			
			// aapt resource value: 0x7f040018
			public const int label_event_manager = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int label_group_manager = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int label_notifications = 2130968598;
			
			// aapt resource value: 0x7f04001a
			public const int label_profile = 2130968602;
			
			// aapt resource value: 0x7f040015
			public const int label_register_account = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int label_reset_password = 2130968599;
			
			// aapt resource value: 0x7f04001c
			public const int label_settings = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int last_name = 2130968612;
			
			// aapt resource value: 0x7f040012
			public const int legend = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int loading = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int messenger_send_button_text = 2130968592;
			
			// aapt resource value: 0x7f04001f
			public const int password = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int reg_legend_text = 2130968610;
			
			// aapt resource value: 0x7f040027
			public const int reg_or_text = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int register = 2130968614;
			
			// aapt resource value: 0x7f040029
			public const int resetpass_legend_text = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int resetpass_send = 2130968618;
			
			// aapt resource value: 0x7f040020
			public const int sign_in = 2130968608;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MessengerButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MessengerButton_Blue = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MessengerButton_Blue_Large = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MessengerButton_Blue_Small = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MessengerButton_White = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MessengerButton_White_Large = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MessengerButton_White_Small = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MessengerButtonText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MessengerButtonText_Blue = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MessengerButtonText_Blue_Large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int MessengerButtonText_Blue_Small = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int MessengerButtonText_White = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MessengerButtonText_White_Large = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int MessengerButtonText_White_Small = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int NoActionBar = 2131165205;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_button_like = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_button_send = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_button_share = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_loginview_default_style = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_loginview_silver_style = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tooltip_bubble_text = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
